seed:
tokenizer_name: chinese_char
dataset_name: asr_dataset
model_name:
optimizer_name:
scheduler_name:
metric_name: cer
save_path: ./outputs/

train_conf:
  batch_size: 32
  max_epoch: 50
  valid_interval: 5
  accum_grad: 4
  grad_clip: 5

tokenizer:
  pad_id: 0
  sos_id: 1
  eos_id: 2
  blank_id: 3
  unk_id: 4

dataset:
  dataset_path: E:/datasets/data_aishell
  manifest_path: ../manifests/aishell
  feature_types: fbank
  sample_rate: 16000
  extractor_conf:
    num_mel_bins: 80
    frame_shift: 10
    frame_length: 25
    dither: 1.0
  speed_perturb: true
  spec_aug: True
  spec_aug_conf:
    max_t_mask: 50
    max_f_mask: 10
    num_t_mask: 2
    num_f_mask: 2

dataloader:
  batch_size: ${train_conf.batch_size}
  num_workers: 0
  pin_memory: True
  drop_last: True

model:
  num_classes: ??
  encoder:
    input_dim: ${dataset.num_mel_bins}
  decoder:
    vocab_size: ${tokenizer.vocab_size}


optimizer:
  lr: 0.001

lr_scheduler:
  warmup_steps: 35000


search_name: greedy_search
search:
  decode_type: ctc
  sos_id: ${tokenizer.sos_id}
  eos_id: ${tokenizer.eos_id}
  pad_id: ${tokenizer.pad_id}
  blank_id: ${tokenizer.blank_id}